# Generated by Django 3.1.4 on 2021-07-25 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='organ',
            name='donar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donar.donar'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='hospital_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organ',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organ',
            name='hospital_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='organ',
            name='organ_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organ',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
